from fastapi import APIRouter

from app.api.v1 import (
    admin,
    alerts,
    audit,
    auth,
    batch,
    data_sources,
    dataset_preparations,
    datasets,
    drift,
    endpoints,
    experiments,
    feedback,
    gate_policies,
    health,
    inference,
    jobs,
    model_quality,
    monitoring,
    pipeline_copilot,
    pipelines,
    projects,
    quality,
    registry,
    retrain,
    schedules,
    service_api_keys,
    splits,
    users,
)

router = APIRouter()

for child_router in (
    health.router,
    auth.router,
    users.router,
    projects.router,
    data_sources.router,
    datasets.router,
    dataset_preparations.router,
    quality.router,
    splits.router,
    jobs.router,
    experiments.router,
    pipelines.router,
    pipeline_copilot.router,
    registry.router,
    gate_policies.router,
    endpoints.router,
    service_api_keys.router,
    inference.router,
    batch.router,
    monitoring.router,
    model_quality.router,
    feedback.router,
    drift.router,
    retrain.router,
    schedules.router,
    alerts.router,
    audit.router,
    admin.router,
):
    router.include_router(child_router)
