#!/bin/bash
# One-shot init for disposable oracle-source (Compose profile: source).
# Seeds MODELFLOW.CUSTOMERS and a SELECT-only reader account.
set -euo pipefail

HOST="${SOURCE_ORACLE_HOST:-oracle-source}"
SYSTEM_PASSWORD="${SOURCE_ORACLE_SYSTEM_PASSWORD:?SOURCE_ORACLE_SYSTEM_PASSWORD is required}"
SERVICE_NAME="${SOURCE_ORACLE_SERVICE_NAME:?SOURCE_ORACLE_SERVICE_NAME is required}"
APP_USER="${SOURCE_ORACLE_APP_USER:?SOURCE_ORACLE_APP_USER is required}"
READER_USER="${SOURCE_ORACLE_USER:?SOURCE_ORACLE_USER is required}"
READER_PASSWORD="${SOURCE_ORACLE_PASSWORD:?SOURCE_ORACLE_PASSWORD is required}"

CONNECT_SYSTEM="system/${SYSTEM_PASSWORD}@//${HOST}/${SERVICE_NAME}"
CONNECT_APP="${APP_USER}/${SOURCE_ORACLE_APP_PASSWORD:-}@//${HOST}/${SERVICE_NAME}"

run_sqlplus() {
  local connect="$1"
  shift
  sqlplus -s "$connect" "$@"
}

echo "Waiting for Oracle at ${HOST}/${SERVICE_NAME}..."
ready=0
for _ in $(seq 1 90); do
  if echo "SELECT 1 FROM dual; EXIT;" | run_sqlplus "$CONNECT_SYSTEM" >/dev/null 2>&1; then
    ready=1
    break
  fi
  sleep 2
done
if [[ "$ready" != "1" ]]; then
  echo "Oracle did not become ready for SYSTEM login." >&2
  exit 1
fi

APP_PASSWORD="${SOURCE_ORACLE_APP_PASSWORD:?SOURCE_ORACLE_APP_PASSWORD is required}"
CONNECT_APP="${APP_USER}/${APP_PASSWORD}@//${HOST}/${SERVICE_NAME}"

echo "Ensuring APP user ${APP_USER} can own CUSTOMERS..."
# APP_USER is created by the gvenzl image via APP_USER env; grant CREATE TABLE if needed.
run_sqlplus "$CONNECT_SYSTEM" <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE
GRANT CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO ${APP_USER};
EXIT;
SQL

echo "Seeding ${APP_USER}.CUSTOMERS..."
run_sqlplus "$CONNECT_APP" <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE customers PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
CREATE TABLE customers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  segment VARCHAR2(64) NOT NULL,
  lifetime_value NUMBER(12, 2) NOT NULL
);
INSERT INTO customers (name, email, segment, lifetime_value) VALUES
  ('Ada Lovelace', 'ada@example.com', 'enterprise', 12500.00);
INSERT INTO customers (name, email, segment, lifetime_value) VALUES
  ('Grace Hopper', 'grace@example.com', 'growth', 7200.50);
INSERT INTO customers (name, email, segment, lifetime_value) VALUES
  ('Alan Turing', 'alan@example.com', 'starter', 1800.75);
COMMIT;
EXIT;
SQL

echo "Creating SELECT-only reader ${READER_USER}..."
# Quoting keeps mixed-case passwords; unquoted identifiers fold to uppercase.
run_sqlplus "$CONNECT_SYSTEM" <<SQL
WHENEVER SQLERROR CONTINUE
DROP USER ${READER_USER} CASCADE;
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE USER ${READER_USER} IDENTIFIED BY "${READER_PASSWORD}";
GRANT CREATE SESSION TO ${READER_USER};
GRANT SELECT ON ${APP_USER}.customers TO ${READER_USER};
EXIT;
SQL

echo "oracle-source init complete."
