#!/usr/bin/env bash
# Generate a local .env for ModelFlow Compose without committing secrets.
# Host tools required: bash, docker (Compose plugin used by verify/up separately).
# Secret generation runs inside a throwaway Python container — no host Python/OpenSSL.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
NON_INTERACTIVE=0

usage() {
  cat <<'EOF'
Usage: ./scripts/init-env.sh [--force] [--non-interactive-test]

Creates .env with required Compose secrets if missing.
  --force                 Overwrite an existing .env
  --non-interactive-test  Skip prompts; use test-friendly defaults (CI / verify)
EOF
}

FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1 ;;
    --non-interactive-test) NON_INTERACTIVE=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
  shift
done

if [[ -f "${ENV_FILE}" && "${FORCE}" != "1" ]]; then
  echo ".env already exists at ${ENV_FILE} (use --force to regenerate)."
  exit 0
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required to generate secrets (no host Python/OpenSSL dependency)." >&2
  exit 1
fi

# Cryptographically strong secrets via official Python image (stdlib secrets only).
readarray -t SECRETS < <(
  docker run --rm python:3.11-slim python - <<'PY'
import secrets
import string

alphabet = string.ascii_letters + string.digits
print(secrets.token_urlsafe(48))
print("mf_" + "".join(secrets.choice(alphabet) for _ in range(40)))
print(secrets.token_urlsafe(32))
print(secrets.token_urlsafe(32))
print(secrets.token_urlsafe(24))
print(secrets.token_urlsafe(24))
PY
)

JWT_SECRET="${SECRETS[0]}"
BOOTSTRAP_PASSWORD="${SECRETS[1]}"
POSTGRES_PASSWORD="${SECRETS[2]}"
MINIO_ROOT_PASSWORD="${SECRETS[3]}"
GRAFANA_ADMIN_PASSWORD="${SECRETS[4]}"
BACKUP_ENCRYPTION_KEY="${SECRETS[5]}"
BOOTSTRAP_USERNAME="admin"

if [[ "${NON_INTERACTIVE}" != "1" ]] && [[ -t 0 ]]; then
  read -r -p "Bootstrap admin username [${BOOTSTRAP_USERNAME}]: " input || true
  BOOTSTRAP_USERNAME="${input:-$BOOTSTRAP_USERNAME}"
  read -r -s -p "Bootstrap admin password (generated if empty): " input || true
  echo
  if [[ -n "${input:-}" ]]; then
    BOOTSTRAP_PASSWORD="${input}"
  fi
fi

RATE_LIMIT=120
if [[ "${NON_INTERACTIVE}" == "1" ]]; then
  RATE_LIMIT=10000
fi

umask 077
cat > "${ENV_FILE}" <<EOF
# Generated by scripts/init-env.sh — do not commit.
POSTGRES_USER=modelflow
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=modelflow
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
JWT_SECRET=${JWT_SECRET}
BOOTSTRAP_ADMIN_USERNAME=${BOOTSTRAP_USERNAME}
BOOTSTRAP_ADMIN_PASSWORD=${BOOTSTRAP_PASSWORD}
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
BACKUP_ENCRYPTION_KEY=${BACKUP_ENCRYPTION_KEY}
RATE_LIMIT_PER_MINUTE=${RATE_LIMIT}
CORS_ORIGINS=http://localhost:3000
EOF

echo "Wrote ${ENV_FILE}"
if [[ "${NON_INTERACTIVE}" == "1" ]]; then
  echo "Non-interactive test mode: RATE_LIMIT_PER_MINUTE=${RATE_LIMIT}"
else
  echo "Bootstrap admin: ${BOOTSTRAP_USERNAME} / (password stored in .env)"
fi
echo "Keep .env private. Rotate secrets before any shared or production use."
